name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update package list
      run: sudo apt-get update
    
    - name: Install TeX Live
      run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends texlive texlive-latex-extra texlive-metapost latexmk
      
    - name: Install Ghostscript
      run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends ghostscript
      
    - name: Compile PDF
      run: make report
