name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install TeX Live
      run: sudo apt-get install texlive texlive-latex-extra latexmk
      
    - name: Install Ghostscript
      run: sudo apt-get install ghostscript
      
    - name: Compile PDF
      run: make report
